version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=devel"
      - "MONGO_INITDB_ROOT_PASSWORD=devel"
  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      - "ME_CONFIG_MONGODB_SERVER=mongodb"
      - "ME_CONFIG_MONGODB_ENABLE_ADMIN=true"
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=devel"