version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=devel"
      - "MONGO_INITDB_ROOT_PASSWORD=devel"